# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(890, 815)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.search_idLE = QtWidgets.QLineEdit(self.centralwidget)
        self.search_idLE.setGeometry(QtCore.QRect(40, 100, 181, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.search_idLE.setFont(font)
        self.search_idLE.setObjectName("search_idLE")
        self.log_outBtn = QtWidgets.QPushButton(self.centralwidget)
        self.log_outBtn.setGeometry(QtCore.QRect(680, 20, 150, 75))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.log_outBtn.setFont(font)
        self.log_outBtn.setObjectName("log_outBtn")
        self.titleLb = QtWidgets.QLabel(self.centralwidget)
        self.titleLb.setGeometry(QtCore.QRect(195, 30, 500, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.titleLb.setFont(font)
        self.titleLb.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLb.setObjectName("titleLb")
        self.friendsLW = QtWidgets.QListWidget(self.centralwidget)
        self.friendsLW.setGeometry(QtCore.QRect(40, 150, 281, 301))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.friendsLW.setFont(font)
        self.friendsLW.setObjectName("friendsLW")
        self.messagesLW = QtWidgets.QListWidget(self.centralwidget)
        self.messagesLW.setGeometry(QtCore.QRect(370, 149, 460, 421))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.messagesLW.setFont(font)
        self.messagesLW.setObjectName("messagesLW")
        self.add_friendBtn = QtWidgets.QPushButton(self.centralwidget)
        self.add_friendBtn.setGeometry(QtCore.QRect(230, 95, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.add_friendBtn.setFont(font)
        self.add_friendBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../src/imgs/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_friendBtn.setIcon(icon)
        self.add_friendBtn.setIconSize(QtCore.QSize(30, 30))
        self.add_friendBtn.setObjectName("add_friendBtn")
        self.sendBtn = QtWidgets.QPushButton(self.centralwidget)
        self.sendBtn.setGeometry(QtCore.QRect(680, 660, 150, 75))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.sendBtn.setFont(font)
        self.sendBtn.setObjectName("sendBtn")
        self.messageTE = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.messageTE.setGeometry(QtCore.QRect(370, 580, 461, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.messageTE.setFont(font)
        self.messageTE.setObjectName("messageTE")
        self.is_textRBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.is_textRBtn.setGeometry(QtCore.QRect(370, 680, 61, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.is_textRBtn.setFont(font)
        self.is_textRBtn.setChecked(True)
        self.is_textRBtn.setObjectName("is_textRBtn")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.is_textRBtn)
        self.is_imageRBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.is_imageRBtn.setGeometry(QtCore.QRect(440, 680, 81, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.is_imageRBtn.setFont(font)
        self.is_imageRBtn.setObjectName("is_imageRBtn")
        self.buttonGroup.addButton(self.is_imageRBtn)
        self.is_fileRBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.is_fileRBtn.setGeometry(QtCore.QRect(520, 680, 61, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.is_fileRBtn.setFont(font)
        self.is_fileRBtn.setObjectName("is_fileRBtn")
        self.buttonGroup.addButton(self.is_fileRBtn)
        self.delete_friendBtn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_friendBtn.setGeometry(QtCore.QRect(280, 95, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.delete_friendBtn.setFont(font)
        self.delete_friendBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../src/imgs/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_friendBtn.setIcon(icon1)
        self.delete_friendBtn.setIconSize(QtCore.QSize(30, 30))
        self.delete_friendBtn.setObjectName("delete_friendBtn")
        self.target_idLb = QtWidgets.QLabel(self.centralwidget)
        self.target_idLb.setGeometry(QtCore.QRect(390, 110, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.target_idLb.setFont(font)
        self.target_idLb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.target_idLb.setObjectName("target_idLb")
        self.groupsLW = QtWidgets.QListWidget(self.centralwidget)
        self.groupsLW.setGeometry(QtCore.QRect(40, 500, 281, 281))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupsLW.setFont(font)
        self.groupsLW.setObjectName("groupsLW")
        self.groupsLb = QtWidgets.QLabel(self.centralwidget)
        self.groupsLb.setGeometry(QtCore.QRect(80, 460, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.groupsLb.setFont(font)
        self.groupsLb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupsLb.setObjectName("groupsLb")
        self.add_groupBtn = QtWidgets.QPushButton(self.centralwidget)
        self.add_groupBtn.setGeometry(QtCore.QRect(200, 455, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.add_groupBtn.setFont(font)
        self.add_groupBtn.setText("")
        self.add_groupBtn.setIcon(icon)
        self.add_groupBtn.setIconSize(QtCore.QSize(30, 30))
        self.add_groupBtn.setObjectName("add_groupBtn")
        self.delete_groupBtn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_groupBtn.setGeometry(QtCore.QRect(250, 455, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.delete_groupBtn.setFont(font)
        self.delete_groupBtn.setText("")
        self.delete_groupBtn.setIcon(icon1)
        self.delete_groupBtn.setIconSize(QtCore.QSize(30, 30))
        self.delete_groupBtn.setObjectName("delete_groupBtn")
        self.emojiBtn = QtWidgets.QPushButton(self.centralwidget)
        self.emojiBtn.setGeometry(QtCore.QRect(590, 660, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.emojiBtn.setFont(font)
        self.emojiBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../src/emoji/0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.emojiBtn.setIcon(icon2)
        self.emojiBtn.setIconSize(QtCore.QSize(36, 36))
        self.emojiBtn.setObjectName("emojiBtn")
        self.emojiLW = QtWidgets.QListWidget(self.centralwidget)
        self.emojiLW.setGeometry(QtCore.QRect(500, 460, 256, 192))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.emojiLW.setFont(font)
        self.emojiLW.setViewMode(QtWidgets.QListView.IconMode)
        self.emojiLW.setObjectName("emojiLW")
        self.videoBtn = QtWidgets.QPushButton(self.centralwidget)
        self.videoBtn.setGeometry(QtCore.QRect(370, 720, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.videoBtn.setFont(font)
        self.videoBtn.setText("")
        self.videoBtn.setIconSize(QtCore.QSize(55, 55))
        self.videoBtn.setCheckable(False)
        self.videoBtn.setObjectName("videoBtn")
        self.audioBtn = QtWidgets.QPushButton(self.centralwidget)
        self.audioBtn.setGeometry(QtCore.QRect(450, 720, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.audioBtn.setFont(font)
        self.audioBtn.setText("")
        self.audioBtn.setIconSize(QtCore.QSize(55, 55))
        self.audioBtn.setObjectName("audioBtn")
        self.voice_to_textBtn = QtWidgets.QPushButton(self.centralwidget)
        self.voice_to_textBtn.setGeometry(QtCore.QRect(530, 720, 60, 60))
        self.voice_to_textBtn.setText("")
        self.voice_to_textBtn.setIconSize(QtCore.QSize(55, 55))
        self.voice_to_textBtn.setFlat(False)
        self.voice_to_textBtn.setObjectName("voice_to_textBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_idLE.setPlaceholderText(_translate("MainWindow", "Enter an id..."))
        self.log_outBtn.setText(_translate("MainWindow", "Log Out"))
        self.titleLb.setText(_translate("MainWindow", "Welcome, user!"))
        self.sendBtn.setText(_translate("MainWindow", "Send"))
        self.is_textRBtn.setText(_translate("MainWindow", "Text"))
        self.is_imageRBtn.setText(_translate("MainWindow", "Image"))
        self.is_fileRBtn.setText(_translate("MainWindow", "File"))
        self.target_idLb.setText(_translate("MainWindow", "ID"))
        self.groupsLb.setText(_translate("MainWindow", "Groups"))


